server:
  port: 8090

spring:
  # 数据源的相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: rootroot
  redis:
    #Redis 单机单实例
    database: 1
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl